### ISSUE TITLE
Infragistics UltraGrid problem - Multiple TestControls found for ControlType...

### ISSUE THREAD

**Issue by blsakj** [TestStack/White#268]
IDE: Visual Studio 2012
Infragistics: 13.2.20132.2042
White: nuget package 0.13.0.0

I am in White quite new and my task was to test White for our purposes
I created empty solution with winform infragistics components.
If you add only ultragrid and execute code below, I receive the following exception
Other tested components we need except ultragrid works well.
Could you give some hint how to use ultragrid ?
Thanks.

---
## Exception:

TestStack.White.Mappings.ControlDictionaryException was unhandled
  HResult=-2146233088
  Message=Multiple TestControls found for ControlType=custom and FrameworkId:WinForm - TestStack.White.UIItems.TableItems.TableHeader, TestStack.White.UIItems.TableItems.TableRow
  Source=TestStack.White
  StackTrace:
       at TestStack.White.Mappings.ControlDictionary.GetTestControlType(String className, String name, ControlType controlType, String frameWorkId, Boolean isNativeControl) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Mappings\ControlDictionary.cs:line 163
       at TestStack.White.Mappings.ControlDictionary.GetTestControlType(AutomationElement automationElement) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Mappings\ControlDictionary.cs:line 219
       at TestStack.White.Factory.DictionaryMappedItemFactory.Create(AutomationElement automationElement, ActionListener actionListener) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Factory\DictionaryMappedItemFactory.cs:line 14
       at TestStack.White.UIItems.UIItemCollection..ctor(IEnumerable automationElements, UIItemFactory uiItemFactory, ActionListener actionListener) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\UIItemCollection.cs:line 37
       at TestStack.White.Finder.CachedUIItems.GetAll(SearchCriteria searchCriteria, ActionListener actionListener, UIItemFactory factory) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Finder\CachedUIItems.cs:line 92
       at TestStack.White.Finder.CachedUIItems.GetAll(SearchCriteria searchCriteria, ActionListener actionListener) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Finder\CachedUIItems.cs:line 69
       at TestStack.White.UIItems.Container.CachedContainerItemFactory.GetAll(SearchCriteria searchCriteria) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\Container\CachedContainerItemFactory.cs:line 31
       at TestStack.White.UIItems.Container.CurrentContainerItemFactory.FindAll() in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\Container\CurrentContainerItemFactory.cs:line 73
       at TestStack.White.UIItems.UIItemContainer.get_Items() in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\UIItemContainer.cs:line 182
       at ConsoleAnpplication1.Program.Main(String[] args) in c:\Users\XXXX\Documents\Visual Studio 2012\Projects\WindowsFormsApplication4\ConsoleApplication1\Program.cs:line 19
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

---
## Code example:

```
     Application application = Application.Launch(@"WindowsFormsApplication4.exe");
     Window window = application.GetWindow("Form1", InitializeOption.WithCache);


     foreach (var item in window.Items) // EXCEPTION is thrown here
     {
        Console.WriteLine(string.Format("AccessKey: {0}",item.AccessKey));
        Console.WriteLine(string.Format("Id: {0}", item.Id));
        Console.WriteLine(string.Format("Name: {0}", item.Name));
        Console.WriteLine(string.Format("ProgrammaticName: {0}", item.AutomationElement.Current.ControlType.ProgrammaticName));
        Console.WriteLine("-------------");
     }
     application.Close();
     Console.ReadLine();
```

**Comment by hwdegroot** [comment]
If you have access tot the source, you can define your own custom UIItem and use   : 

    [ControlTypeMapping(CustomUIItemType.Custom)]

instead of 

    [ControlTypeMapping(CustomUIItemType.Table)]

or

    [ControlTypeMapping(CustomUIItemType.DataGrid)]

works for me

**Comment by qualityking** [comment]
Hi  hwdegroot,
Can you please explain with complete example how to define a custom control
I want to use this with devexpress gridcontrol and custom combobox, i have the code with me for casting custom control with the devexpress control type

Thanks,
Manish Bansal
