### ISSUE TITLE
Problem With ListViewCell access

### ISSUE THREAD

**Issue by magnifyingone** [TestStack/White#284]
Hi!

I'm trying to access to ListViewCell like this: templateGrid.Row("Currency", rowindex).Cells[2].Click();

If there is a value in the cell, everything goes ok. But if there is a null value, I've got exception:
WhiteException was unhandled by user code: Failed to click on ListViewCell. AutomationId:, Name:, ControlType:text, FrameworkId:WPF, bounds empty.

   at TestStack.White.UIItems.UIItem.PerformClick() in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\UIItem.cs:line 265
   at TestStack.White.UIItems.UIItem.PerformIfValid(Action action) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\UIItem.cs:line 243
   at TestStack.White.UIItems.UIItem.Click() in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\UIItem.cs:line 232

Sorry if this is not a bug and missunderstood something. If it is so - please advice how can I access to an editable cell of a ListViewRow item.

**Comment by maxinfet** [comment]
I attempted to recreate this using the WpfTestApplication in TestStack.White.TestApps.WpfTestApplication. I was unable to replicate using a sample application I built. Could you share some more information about the application you are attempting to automate and what kind of control it is, like if it is a standard listview or maybe an infragistics control?

    using System.Windows;
    using TestStack.White.UIItems;
    using TestStack.White.UIItems.TabItems;
    using Application = TestStack.White.Application;

    namespace MyTestApp
    {
       public partial class MyTestWindow : Window
       {
            public MyTestWindow()
            {
                InitializeComponent();
            }

            private void Button_Click(object sender, RoutedEventArgs e)
            {
                Application application = Application.Attach("WpfTestApplication");
                var window = application.GetWindow("MainWindow");

                var tabControl = window.Get<Tab>("ControlsTab");
                tabControl.SelectTabPage("Data Grid");

                var dataGridControl = window.Get<ListView>("DataGridControl");
                dataGridControl.Rows[1].Cells[2].DoubleClick();
            }
        }
    }
