### ISSUE TITLE
Unhandled Exception: Type Initialization Exception accessing

### ISSUE THREAD

**Issue by nickworm** [TestStack/White#312]
.NET 4.0 Application and LIbrary
Castle.Core - 3.3.0.0
TestStack.White - 0.13.0.0

// *** Code Snippet ***
var varApp = TestStack.White.Application.Launch("wordpad");
TestStack.White.Application target = TestStack.White.Application.Attach("wordpad");

// The following line throws the exception detailed at the bottom of this issue.
TestStack.White.UIItems.WindowItems.Window window = target.GetWindow("Document - WordPad");
Console.WriteLine(target.Name);
target.KillAndSaveState();
// *** End Code Snippet ***

When I stepped into the GetWindow() I found that the following static member "White.Application.Desktop" was null but should have been initialized.

The "Desktop" member is only NULL when executing from my application but I can create a simple test application (library and winform projects) utilizing the references provided by NuGet package manager (same as my application) and it works just fine.

Are there any limitations or incompatibilities that may not be documented?

Thank you for your help and attention!

--------- Exception Stack Trace --------- 
Exception Stack trace:
The type initializer for 'TestStack.White.Desktop' threw an exception.
The handle is invalid.
TypeInitializationException: The type initializer for 'TestStack.White.Desktop' threw an exception.
StackTrace:
     at TestStack.White.UIItems.WindowItems.Window.InitializeWindow() in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\WindowItems\Window.cs:line 70
     at TestStack.White.UIItems.WindowItems.Window..ctor(AutomationElement automationElement, ActionListener actionListener, InitializeOption initializeOption, WindowSession windowSession) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\WindowItems\Window.cs:line 63
     at TestStack.White.UIItems.WindowItems.Window..ctor(AutomationElement automationElement, InitializeOption initializeOption, WindowSession windowSession) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\WindowItems\Window.cs:line 57
     at TestStack.White.UIItems.WindowItems.Win32Window..ctor(AutomationElement automationElement, WindowFactory windowFactory, InitializeOption option, WindowSession windowSession) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\WindowItems\Win32Window.cs:line 20
     at TestStack.White.Factory.ChildWindowFactory.Create(AutomationElement element, InitializeOption option, WindowSession windowSession) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Factory\ChildWindowFactory.cs:line 59
     at TestStack.White.Factory.WindowFactory.CreateWindow(String title, Process process, InitializeOption option, WindowSession windowSession) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Factory\WindowFactory.cs:line 76
     at TestStack.White.Application.GetWindow(String title, InitializeOption option) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Application.cs:line 181
     at TestStack.White.Application.GetWindow(String title) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Application.cs:line 192
*INTERNAL TRACES REMOVED*

  Inner IOException: The handle is invalid.
     StackTrace:
     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
     at System.IO.__ConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
     at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
     at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
     at System.IO.TextWriter.WriteLine(String value)
     at System.IO.TextWriter.WriteLine(String format, Object[] arg)
     at System.IO.TextWriter.SyncTextWriter.WriteLine(String format, Object[] arg)
     at TestStack.White.Configuration.WhiteDefaultLogger.Log(LoggerLevel loggerLevel, String loggerName, String message, Exception exception) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Configuration\WhiteDefaultLogger.cs:line 40
     at Castle.Core.Logging.LevelFilteredLogger.Log(LoggerLevel loggerLevel, String message, Exception exception)
     at Castle.Core.Logging.LevelFilteredLogger.InfoFormat(String format, Object[] args)
     at TestStack.White.Bricks.AssemblyConfiguration..ctor(String sectionGroup, String sectionName, Dictionary`2 defaultValues, ILogger logger) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Bricks\AssemblyConfiguration.cs:line 24
     at TestStack.White.Configuration.UIItemIdAppXmlConfiguration..ctor() in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Configuration\UIItemIdAppXmlConfiguration.cs:line 29
     at TestStack.White.Configuration.UIItemIdAppXmlConfiguration.get_Instance() in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Configuration\UIItemIdAppXmlConfiguration.cs:line 26
     at TestStack.White.UIItems.Scrolling.ScrollBars.FindHorizontalBar(FindElement findElement) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\Scrolling\ScrollBars.cs:line 28
     at TestStack.White.UIItems.Scrolling.ScrollBars.get_Horizontal() in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\Scrolling\ScrollBars.cs:line 24
     at TestStack.White.UIItems.Scrolling.AbstractScrollBars.get_CanScroll() in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\Scrolling\IScrollBars.cs:line 17
     at TestStack.White.UIItems.UIItemContainer.HasActionInterceptionBehaviour() in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\UIItemContainer.cs:line 172
     at TestStack.White.UIItems.UIItemContainer.get_ChildrenActionListener() in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\UIItemContainer.cs:line 167
     at TestStack.White.UIItems.UIItemContainer..ctor(AutomationElement automationElement, ActionListener actionListener, InitializeOption initializeOption, WindowSession windowSession) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\UIItemContainer.cs:line 40
     at TestStack.White.Desktop..ctor(AutomationElement automationElement, ActionListener actionListener, InitializeOption initializeOption, WindowSession windowSession) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Desktop.cs:line 25
     at TestStack.White.Desktop.Create() in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Desktop.cs:line 22
     at TestStack.White.Desktop..cctor() in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Desktop.cs:line 17

**Comment by maxinfet** [comment]
Are you excuting your application while the screen is locked or from a service? The only case I know of that will result in a null root element is a locked screen or running from a context that has no desktop.

**Comment by ivan-danilov** [comment]
@maxinfet I guess we might have catched the exception somewhere near the start in such cases and wrap it with another one with better message explaining the problem.
