### ISSUE TITLE
button click throws "ElementNotAvailableException: The target element corresponds to UI that is no longer available (for example, the parent window has closed)" exception

### ISSUE THREAD

**Issue by KunQian2** [TestStack/White#409]
hi,

When clicking on button in my test script, sometimes I get "ElementNotAvailableException: The target element corresponds to UI that is no longer available (for example, the parent window has closed)" exception. In the test script I open "Open File" dialog box, and then click on some buttons in my application under test. The exception is intermittent. I tried to call ReloadIfCached on the window and RaiseClickEvent, none helped. Please let me know how I can get around this problem.

thanks,
Kun

**Comment by dpisanu** [comment]
it's hard to debug this without having the test code and the application at hand.
Do you maybe have a slimmed down version of the application at hand that you can provide alongside the test or are you able to reproduce this with a stupid simple empty ui demo that you can run your test on?

ideally it is always best to locate your UI items right hand before you need it to avoid running into the situation that it might not be there anymore by the time you try to access it.

**Comment by anileapen** [comment]
Hi ,
I am also getting this error intermittently. The error is : 
Result Message:	
System.InvalidOperationException : The target element corresponds to UI that is no longer available (for example, the parent window has closed).
   at MS.Internal.AutomationProxies.WindowsTreeView.TreeViewItem.CheckForElementAvailable()
   at MS.Internal.AutomationProxies.WindowsTreeView.TreeViewItem.get_BoundingRectangle()
   at MS.Internal.AutomationProxies.WindowsTreeView.TreeViewItem.IsOffscreen()
   at MS.Internal.AutomationProxies.ProxySimple.GetElementProperty(AutomationProperty idProp)
   at MS.Internal.AutomationProxies.WindowsTreeView.TreeViewItem.GetElementProperty(AutomationProperty idProp)
   at MS.Internal.AutomationProxies.ProxySimple.System.Windows.Automation.Provider.IRawElementProviderSimple.GetPropertyValue(Int32 propertyId)
I am using Winium and Selenium with c#
Can you help please?
