### ISSUE TITLE
Test execution under Windows 10 is very slow

### ISSUE THREAD

**Issue by chruah** [TestStack/White#466]
Hallo,

I had implemented tests for a wpf application under windows 7 and updated my system to windows 10.
After this the test execution time is more or less four times higher.

To find the ui items I use the get<...> and exists functions and as search criteria the automation id of the ui item. Has somebody facing the same issue or have a clue what I can do to fix it.

**Comment by tlbzeu** [comment]
U can try to use UIAComWrapper branch and see if it is better :)

**Comment by huserben** [comment]
Hi
I think I have the same issue. My tests run on a Windows 7 machine smoothly but some of them fail because it cannot find an element. I quickly tried with the dll's from the UIAComWrapper branch and it seemed to work better there.

Is there any plan on merging this things back to the main branch in the near future? Or would we need to change this manually now in our project (instead of using the nuget package...).

Thanks for your help

**Comment by tlbzeu** [comment]
Hi
There is a nuget package for UIA3 : 
Install-Package TestStack.White.Uia3 -Pre

**Comment by huserben** [comment]
Hi

I integrated now the nuget package and still everything works fine on Windows 7. On Windows 10 all the tests succeed if I run them one by one. But when I run multiple in a row, only the first one succeeds and the second one then throws the following exception:
![teststack_issue](https://cloud.githubusercontent.com/assets/5486874/18908657/c3e1432a-8570-11e6-8567-608cf1634cf1.PNG)


This happens when i get the main window of the application that was started and it is the exact same code that runs successful in the first test...
application = Application.Launch(path);
mainWindow = application.GetWindow(MainWindowTitle);

Do you know what the problem could be?

Thanks for your help

**Comment by tlbzeu** [comment]
either you need to kill the application after the first test, or you can add this so you don`t need to start the app again:
```
var psi = new ProcessStartInfo(path);
application = Application.AttachOrLaunch(psi);
mainWindow = application.GetWindow(MainWindowTitle);
```

**Comment by huserben** [comment]
Hi

I do close the application after each test (it is implemented as IDisposable and in the Dispose we close it...). I use both application.Close() and later on the Kill().
But I tried as well via the AttachOrLaunch and the same Exception still happens...

Maybe the CallStack can help:
   at UIAutomationClient.IUIAutomationElement.GetCurrentPropertyValueEx(Int32 propertyId, Int32 ignoreDefaultValue)
   at System.Windows.Automation.AutomationElement.GetCurrentPropertyValue(AutomationProperty property, Boolean ignoreDefaultValue) in d:\dev\UIAComWrapper\UiaComWrapper\AutomationElement.cs:line 294
   at System.Windows.Automation.AutomationElement.GetCurrentPropertyValue(AutomationProperty property) in d:\dev\UIAComWrapper\UiaComWrapper\AutomationElement.cs:line 286
   at System.Windows.Automation.AutomationElement.GetPropertyValue(AutomationProperty property, Boolean cached) in d:\dev\UIAComWrapper\UiaComWrapper\AutomationElement.cs:line 312
   at System.Windows.Automation.AutomationElement.AutomationElementInformation.get_BoundingRectangle() in d:\dev\UIAComWrapper\UiaComWrapper\AutomationElement.cs:line 683
   at TestStack.White.UIItems.UIItem.get_Bounds() in C:\projects\white-9yaco\src\TestStack.White\UIItems\UIItem.cs:line 225
   at TestStack.White.UIItems.WindowItems.Window.InitializeWindow() in C:\projects\white-9yaco\src\TestStack.White\UIItems\WindowItems\Window.cs:line 75
   at TestStack.White.UIItems.WindowItems.Window..ctor(AutomationElement automationElement, IActionListener actionListener, InitializeOption initializeOption, WindowSession windowSession) in C:\projects\white-9yaco\src\TestStack.White\UIItems\WindowItems\Window.cs:line 68
   at TestStack.White.UIItems.WindowItems.Window..ctor(AutomationElement automationElement, InitializeOption initializeOption, WindowSession windowSession) in C:\projects\white-9yaco\src\TestStack.White\UIItems\WindowItems\Window.cs:line 63
   at TestStack.White.Factory.ChildWindowFactory.Create(AutomationElement element, InitializeOption option, WindowSession windowSession) in C:\projects\white-9yaco\src\TestStack.White\Factory\ChildWindowFactory.cs:line 59
   at TestStack.White.Factory.WindowFactory.CreateWindow(String title, Process process, InitializeOption option, WindowSession windowSession) in C:\projects\white-9yaco\src\TestStack.White\Factory\WindowFactory.cs:line 75
   at TestStack.White.Application.GetWindow(String title, InitializeOption option) in C:\projects\white-9yaco\src\TestStack.White\Application.cs:line 197
   at TestStack.White.Application.GetWindow(String title) in C:\projects\white-9yaco\src\TestStack.White\Application.cs:line 208

**Comment by huserben** [comment]
Hi again

I tried to reproduce the error with a sample application, but there no exception happens. Could you maybe hint me a bit in what could cause this issue that i can dig into why it is happening when we run a second test run? Because it doesn't seem to make much sense to me the way it is behaving right now. The application is closed after each test and then launched newly. I can as well browse to the application with the UIAVerify tool on the new instance (the one that stays open becuase the test crashes...). As White uses the same base as far as I know it should then work as well with it or am I mistaken?...

Thanks

**Comment by Tyrrrz** [comment]
@huserben 
Any chance you found a way to fix the issue you were having?

**Comment by huserben** [comment]
Hi
I tried back then to find the problem, but i failed and right now we run our tests just on a Windows 7 machine. I think however that it must be related to the application under test as I could not reproduce the problem with a sample project.

Anyway in our environment there will soon come a change to Windows 10 and latest by then we will probably start investigating it again. If I would find anything I would let you now.

**Comment by Tyrrrz** [comment]
Yeah I had the same problem, everything was working with a sample project.
Please do let me know if you managed to get it fixed somehow.

**Comment by arkadioosz** [comment]
Hello.
I'm facing this issue as well. Problem appeared after switching framework from master branch to UIAComWrapper branch. I switched because of perfomance, tests are running nearly 3 times faster with UIAComWrapper version.
I have UI tests grouped with categories, from VS I'm able to run entire group without problem. When running with mstest from command line first test passes through, all other fail (although AUT starts properly). Any new ideas ?

**Comment by arkadioosz** [comment]
Hi again
I didn't solve the problem with the "Value does not fall within the expected range" exception, but I found a workaround. I'm using vstest instead of mstest when running tests from Jenkins. So far seems to work fine. I also did some quick test with nunit console runner and this one also works fine.

**Comment by Tyrrrz** [comment]
Can confirm, works fine in vstest.

**Comment by kevinheyvaert** [comment]
Anybody that has figured this out yet? I see the same things when using FlaUI lib and is terribe runtime on WIndows 10 compared to Windows 7 (40% longer on WIndows 10)
