### ISSUE TITLE
mainWindow.Get<Window>("MyForm"); always throws exception

### ISSUE THREAD

**Issue by Tarascs** [TestStack/White#526]
A line of code:
`var myForm = mainWindow.Get<Window>("MyForm");`

Always throws exception "Must specify at least two conditions."

But there are two conditions: Type and AutomationId.

**Comment by slavikdev** [comment]
I get the same exception attempting to find a popup menu:
```
var print_menu = _window.Get<PopUpMenu>(
   SearchCriteria.ByAutomationId( "PrintMenu" )
);
```

```
System.ArgumentException : Must specify at least two conditions.
   at TestStack.White.UIItems.UIItemContainer.Get(SearchCriteria searchCriteria, TimeSpan timeout) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\UIItemContainer.cs:line 132
   at TestStack.White.UIItems.UIItemContainer.Get[T](SearchCriteria searchCriteria) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\UIItemContainer.cs:line 60
   at Tests.UI.Automation.Windows.MainWindowAutomated.get_LogRecordsViewMenu() in c:\Users\Slava\Documents\projects\clients\Lenco\lenco-autoprint\Autoprint\Tests\UI\Automation\Windows\MainWindowAutomated.cs:line 59
   at Tests.UI.MainWindowTest.TestPrintItem() in c:\Users\Slava\Documents\projects\clients\Lenco\lenco-autoprint\Autoprint\Tests\UI\MainWindowTest.cs:line 90
--ArgumentException
   at System.Windows.Automation.OrCondition..ctor(Condition[] conditions)
   at TestStack.White.UIItems.Finders.OrSearchCondition.get_AutomationCondition() in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\Finders\OrSearchCondition.cs:line 27
   at TestStack.White.UIItems.Finders.SearchConditions.<>c__DisplayClass1.<get_AutomationCondition>b__0(SearchCondition condition) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\Finders\SearchConditions.cs:line 18
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at TestStack.White.UIItems.Finders.SearchConditions.get_AutomationCondition() in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\Finders\SearchConditions.cs:line 21
   at TestStack.White.Factory.PrimaryUIItemFactory.Create(SearchCriteria searchCriteria, ActionListener actionListener) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Factory\PrimaryUIItemFactory.cs:line 74
   at TestStack.White.UIItems.Container.ContainerItemFactory.Get(SearchCriteria searchCriteria, ActionListener uiItemActionListener) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\Container\ContainerItemFactory.cs:line 13
   at TestStack.White.Utility.Retry.For[T](Func`1 getMethod, Predicate`1 shouldRetry, TimeSpan retryFor, Nullable`1 retryInterval) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Utility\Retry.cs:line 138
   at TestStack.White.UIItems.UIItemContainer.Get(SearchCriteria searchCriteria, TimeSpan timeout) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\UIItemContainer.cs:line 109
```

I tried specifying multiple search criteria—same exception. Basically any criteria result into the same exception, even when I specify incorrect automation ID.

**Comment by slavikdev** [comment]
I’m sorry, it looks like I didn’t use correct approach to get popup menu. There’s a ``Popup`` property of the ``Window`` class which should be used to get active context menu:
```
private readonly Window _window;
....
....
var print_menu = _window.Popup;
```
