### ISSUE TITLE
Select Header item in a grid(Devexpress)

### ISSUE THREAD

**Issue by MonoAutomation** [TestStack/White#542]
Hello,
I would like to know ,how we can select Header item from a DXGrid  using teststack white/uiautomaiton? i have tried but couldn't able to select any header items. these headers items are Tabs(may be ribbons tabs)
Environment: WPF,Devexpress,ribbons

code looks like(application)
<CustomControl....
<Grid>
    <dx:DXTabControl Name="dxTabControl1">
        <dx:DXTabControl.Resources>
            <Style TargetType="dx:DXTabItem">
                ....
            </Style>
        </dx:DXTabControl.Resources>
        **<dx:DXTabItem Header="dxTabItem1" Name="dxTabItem1" />
        <dx:DXTabItem Header="dxTabItem2" Name="dxTabItem2" />**
                                ...
	</dx:DXTabControl>
</Grid>

i could able see number of headers in the grid but not able to perform select /invoke any action.

Note:Header items are Tabs. using UIAverify also not supported to highlight the elements(tabs/headers)

Can any one please,help me to overcome from this issues....almost blocked all my work due this issue.

**Comment by Roemer** [comment]
Please post a screenshot of Inspect/UIAVerify/FlaUInspect.

**Comment by MonoAutomation** [comment]
I tried to attaching image/screenshot ,but due to security issues not able to attach the screenshot, but whatever i posted the code above...similar to that code only
ex: i want to select tab1 from the header
<dx:DXTabItem Header="Tab 1">

**Comment by MonoAutomation** [comment]
![Uploading Grid.png…]()

**Comment by MonoAutomation** [comment]
Any solution to the above query sir?....plz its blocked all my UIautomation....cant step back to switch some commercial tools...assist me to fix it.

**Comment by Roemer** [comment]
The image is still broken. Please fix it so we can help better.

**Comment by MonoAutomation** [comment]
![ribbontab](https://cloud.githubusercontent.com/assets/1586248/24207657/78b6c986-0f47-11e7-93ac-36fc0f2c362d.jpg)
![grid](https://cloud.githubusercontent.com/assets/1586248/24207866/100a0c58-0f48-11e7-892d-f3b67e7f68cd.jpg)


Even in case of few grids having rows and columns with records, returning empty/null value when i try to get using Automation element.

can you look this issue as well?

Thanks IN advance.

**Comment by dpisanu** [comment]
Looks like a heavy customized and styled control.
I would suggest to look for "datagrid" control. That search from there on
for the correct "pane" control.
Starting from "pane" look for all ControlType.HeaderItem s.
Each header item obviously in itself also contains items. Most notably the
text control.

You have to follow the tree if a control looks like a standard one but
obviously is not.

Be happy that DevExpress is so open. There are much worse vendors out there
like SyncFusion.


Am 22.03.2017 17:14 schrieb "MonoAutomation" <notifications@github.com>:

[image: ribbontab]
<https://cloud.githubusercontent.com/assets/1586248/24207657/78b6c986-0f47-11e7-93ac-36fc0f2c362d.jpg>
[image: grid]
<https://cloud.githubusercontent.com/assets/1586248/24207866/100a0c58-0f48-11e7-892d-f3b67e7f68cd.jpg>

Even in case of few grids having rows and columns with records, returning
empty/null value when i try to get using Automation element.

can you look this issue as well?

Thanks IN advance.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TestStack/White/issues/542#issuecomment-288452165>, or mute
the thread

**Comment by MonoAutomation** [comment]
I traversed from GRID to right PANE and found required header item but no pattern supported to click or select (frankly if i say no pattern displayed for header item) so am facing difficult to select any ribbon tab. yes in my application there so many customized and sylished control (they are all dynamically loaded control based on user action)

in one of the PANE, need to click on buttons but no way to identify that element since white/UIA.not able to recognize them.

i have mentioned already that ,there are GRIDS loaded with data but automation element returns always null. 

am struggling to fix all these issues.

i hope this is the place to get right solution from right people

**Comment by Roemer** [comment]
I know that devexpress grids are not very good with invoke. You mostly need to use mouse clicks on the elements. Also there is a flag in devexpress which disables some features of uia. In FlaUIs faq is that described. See https://github.com/Roemer/FlaUI/wiki/FAQ.
Since you're using WPF I highly suggest you use UIA3 either by using the partially working brach of White or the fully working FlaUI.UIA3 library (see https://github.com/Roemer/FlaUI). I'm using it very successfully with DevExpress.

**Comment by MonoAutomation** [comment]
How to install FlaUInspect ,any way through nuget? 

can you provide detailed steps? 

i tried to compile FlaUI but many error  as below
Error	297	Invalid token ';' in class, struct, or interface member declaration	C:\Users\ohm\Downloads\FlaUI-master\FlaUI-master\src\FlaUI.UIA3\Patterns\StylesPattern.cs	33	71	FlaUI.UIA3

Error	302	; expected	C:\Users\ohm\Downloads\FlaUI-master\FlaUI-master\src\FlaUI.UIA3\UIA3PatternLibrary.cs	34	38	FlaUI.UIA3

Am i missing anything? re added UIcore/2/3. but still the same issue.

**Comment by Roemer** [comment]
FlaUInspect is on chocolatey.org. FLaUI itself is on NuGet or needs Visual Studio 2015 if you want to compile it yourself.

**Comment by MonoAutomation** [comment]
This is the code i have tried to select the item,i could able to see the name of the item but problem to perform action.

```
var searchCriteriagrid = SearchCriteria.ByControlType(ControlType.DataGrid).AndAutomationId("gridGeneration");
            var dxTabs = MainWindow.Get<MyGridUIItem>(searchCriteriagrid);
            AutomationElement gEle = dxTabs.AutomationElement;
            GridPattern gpat = (GridPattern)gEle.GetCurrentPattern(GridPattern.Pattern);

                Condition headerPanel = new AndCondition(
    new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.Pane),
            new PropertyCondition(AutomationElement.AutomationIdProperty, "gridGeneration"));

                Condition headerItem = new PropertyCondition(AutomationElement.ControlTypeProperty, ControlType.HeaderItem);


                AutomationElement eleHeaderPan = dxTabs.AutomationElement.FindFirst(TreeScope.Children, headerPanel);
                while (eleHeaderPan != null)
                {
                    AutomationElementCollection hItems = eleHeaderPan.FindAll(TreeScope.Children, headerItem);
                    foreach (AutomationElement hItem in hItems)
                    {
                        string tye = hItem.Current.Name;
                        if ( tye.ToLower().Contains("platform"))
                         {
                             
                             DockPosition setpos = (DockPosition)hItem.GetCurrentPropertyValue(DockPattern.DockPositionProperty, true);
                             DockPattern valPat = (DockPattern)hItem.GetCurrentPattern(DockPattern.Pattern);
                             valPat.SetDockPosition(setpos);
                             
                         }
                    }
                }
```

**Comment by Roemer** [comment]
Can you specify a bit more what exactly fails and what error you get?
In FlaUI (1.0.0-rc1), the code above would look something like that:
```csharp
var app = Application.Launch("your.exe");
using (var uia = new UIA3Automation())
{
    var mainWindow = app.GetMainWindow(uia);
    var grid = mainWindow.FindFirstDescendant(cf =>
        cf.ByControlType(ControlType.DataGrid)
        .And(cf.ByAutomationId("gridGeneration"))
    ).AsGrid();
    var headerPane = grid.FindFirstChild(cf => cf.ByName("HeaderPanel"));
    var headerItems = headerPane.FindAllChildren();
    foreach (var headerItem in headerItems)
    {
        if (headerItem.Properties.Name.Value.ToLower().Contains("platform"))
        {
            var dockPattern = headerItem.Patterns.Dock.Pattern;
            var setPos = dockPattern.DockPosition.Value;
            dockPattern.SetDockPosition(setPos);
            break;
        }
    }
}
```

**Comment by MonoAutomation** [comment]
Getting error,
An exception of type 'System.Runtime.InteropServices.COMException' occurred in FlaUI.UIA3.dll but was not handled in user code

Additional information: An event was unable to invoke any of the subscribers (Exception from HRESULT: 0x80040201)

at 
var app = Application.Launch(@"C:\HOMEWARE\cty\CTY.Octane\CTY.Octane.exe");
            using (var uia = new UIA3Automation())
            {
                **var mainWindow = app.GetMainWindow(uia);** //here am getting the above error.

Exception:
System.Runtime.InteropServices.COMException was unhandled by user code
  HResult=-2147220991
  Message=An event was unable to invoke any of the subscribers (Exception from HRESULT: 0x80040201)
  Source=interop.UIAutomationCore
  ErrorCode=-2147220991
  StackTrace:
       at interop.UIAutomationCore.CUIAutomationClass.ElementFromHandle(IntPtr hwnd)
       at FlaUI.UIA3.UIA3Automation.FromHandle(IntPtr hwnd)
       at FlaUI.Core.Application.GetMainWindow(AutomationBase automation)
       at UIApro.UnitTest1.TestMethod1() in d:\rchintak063014\otn_desktop-master\Source\UIApro\UIApro\UnitTest1.cs:line 25
  InnerException:

**Comment by MonoAutomation** [comment]
the above old code which ever i shared is running fine and clicking somewhere on the application but not on the required tab.

**Comment by Roemer** [comment]
Seems like a race condition. Maybe you have a login dialog or splash screen or something. Try using the TopLevelWindows in the app variable instead of the main window.

**Comment by MonoAutomation** [comment]
no luck, Docpattern...clicking some where..so need to search for other ways to fix it.

**Comment by MonoAutomation** [comment]
Any one have any idea or suggestions to fix the issue?

**Comment by Roemer** [comment]
Is the tab you're trying to click offscreen? If so, you need to bring it into screen first.

**Comment by MonoAutomation** [comment]
I haven't checked this offscreen or not, but if yes how can i bring it to front? is this ok ?
bool ret=Tab.Isoffscreen
var pattern = Tab.AutomationElement.GetCurrentPattern(System.Windows.Automation.InvokePattern.Pattern);
(pattern as System.Windows.Automation.InvokePattern).Invoke();

or is there any work around to bring the element to front?

**Comment by Roemer** [comment]
Depending on the element, you can use the ScrollIntoView from the ScrollItemPattern. Otherwise you probably need to scroll the view manually until the item is visible (IsOffscreen property is set to false).

**Comment by MonoAutomation** [comment]
Yes Roemer,all tabs and other elements are in OFFSCREEN. though after i clicked/focused on any element the UIA spy showing still in offscreen mode. so can you please suggest some working solution to fix ..i don't have much idea on it.

**Comment by Roemer** [comment]
Hard to tell. As far as I have seen in the "screenshots" above, the header items do not support the ScrollItemPattern (which would be the easiest). What you could to is using the scrollbar and scroll to the right or use the keyboard and press "right" until the item you want is on screen.

**Comment by dpisanu** [comment]
It's difficult to give you a working solution without having a working copy
of the problem at hand.

Any way you can provide a skeleton construct of your tool that shows the
problem without containing any company specifics that you obviously would
not want to share?

We usually have a stripped down skeleton of our tools at hand for
showcases, POCs and bug analysis when talking to 3rd party supliers like
DevExpress and Telerik.

Makes analysis so much easier.

Am 06.04.2017 14:11 schrieb "MonoAutomation" <notifications@github.com>:

**Comment by MonoAutomation** [comment]
The code looks lie as below,
<dx:DXWindow
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:dx="http://schemas.devexpress.com/winfx/2008/xaml/core" 
        xmlns:dxe="http://schemas.devexpress.com/winfx/2008/xaml/editors"
        xmlns:dxb="http://schemas.devexpress.com/winfx/2008/xaml/bars"
        xmlns:dxcn="http://schemas.devexpress.com/winfx/2008/xaml/core/internal" 
        xmlns:dxmvvm="http://schemas.devexpress.com/winfx/2008/xaml/mvvm"
        dx:ThemeManager.ThemeName="Office2013"
        x:Class="DXTabControlExample.MainWindow"
        Title="MainWindow" Height="350" Width="550">
    <Grid>
        <dx:DXTabControl Name="tabControl">
            <dx:DXTabItem Header="System">
                <dx:DXTabItem.HeaderTemplate>
                    <DataTemplate>
                        <Grid>
                            <Grid.RowDefinitions>
                                <RowDefinition/>
                                <RowDefinition/>
                            </Grid.RowDefinitions>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition/>
                                <ColumnDefinition/>
                            </Grid.ColumnDefinitions>
                            <TextBlock Text="{Binding}" Grid.ColumnSpan="2"/>
                            <TextBlock Text="State:" Grid.Row="1"/>
                            <Image Source="{dx:DXImage Image=Apply_16x16.png}"  Grid.Row="1" Grid.Column="1" Margin="5,0,0,0"/>
                        </Grid>
                    </DataTemplate>
                </dx:DXTabItem.HeaderTemplate>
            </dx:DXTabItem>
            <dx:DXTabItem Header="Report" Glyph="{dx:DXImage Image=Report_16x16.png}">
                <dx:DXTabItem.GlyphTemplate>
                    <DataTemplate>
                        <Border Background="Green">
                            <Image Source="{Binding}" Margin="0,0,0,0"/>
                        </Border>
                    </DataTemplate>
                </dx:DXTabItem.GlyphTemplate>
            </dx:DXTabItem>
        </dx:DXTabControl>
    </Grid>
</dx:DXWindow>

Can you guide me how can i select Report?
