### ISSUE TITLE
Pretty much everything is broken for items with FrameworkId == "XAML".

### ISSUE THREAD

**Issue by BrainSlugs83** [TestStack/White#559]
TestStack.White has a lot of trouble with windows and controls with a FrameworkId of "XAML".

Trying to get the windows of an application by process Id just plain doesn't work, and getting the window from the desktop works okay, but it won't have any controls on it (except for the usual suspects, like the minimize / maximize buttons, etc.).

I pretty much have to resort to using the `AutomationElementFinder` to get controls from those windows.
I can usually cast it back to a button or some such via `new Button(automationElement, window.ActionListener);` -- so that's annoying but not blocking.

**But** there's absolutely no way to get modal dialog windows that pop-up.  -- If you try to call `window.ModalWindows()` it will crash with an exception like this:

```
Unhandled Exception: System.ArgumentException: 'XAML' is not a valid frameworkId
   at TestStack.White.UIItems.WindowsFrameworkExtensions.FromFrameworkId(String frameworkId) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\WindowsFrameworkExtensions.cs:line 35
   at TestStack.White.Factory.ChildWindowFactory.Create(AutomationElement element, InitializeOption option, WindowSession windowSession) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\Factory\ChildWindowFactory.cs:line 56
   at TestStack.White.UIItems.WindowItems.Window.<ModalWindows>b__10(AutomationElement descendant) in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\WindowItems\Window.cs:line 433
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at TestStack.White.UIItems.WindowItems.Window.ModalWindows() in c:\TeamCity\buildAgent\work\89a20b30302799e\src\TestStack.White\UIItems\WindowItems\Window.cs:line 432
   at ScreenAuto.Program.Main(String[] args) in C:\projects.temp\ScreenAuto\ScreenAuto\Program.cs:line 169
```

I can get the modal windows automation elements via `AutomationElementFinder`, but it seems impossible convert that back to a Window object via the public API that TestStack.White provides. :(

**Comment by BrainSlugs83** [comment]
For reference; this should work on any windows 10 system to get you a very broken window object:

```
 Process.Start("ms-settings:about");
 var window = Desktop.Instance.Windows().Where(x => string.Equals(x.Name, "Settings")).Single();
```

If you look in the raw automation element controls you will see a ton in there, but `window.Items` has like nothing.

I've seen a lot of really similar behavior with other `XAML` based stuff; things that show up totally fine in `Inspect.exe` but that don't show up at all to TestStack.White.

**Comment by Roemer** [comment]
Framework ```XAML``` usally means it's an UWP app. Unfortunately, UWP apps do not work really good with UIA2 (which the default White is based on). You can try the experimental ```UIAComWrapper``` branch which was a try to convert White to UIA3. Probably a better alternative would be to switch to another framework which fully supports UIA3 (like https://github.com/Roemer/FlaUI).
